# permissions to do edit kobuilders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kobuilder-editor-role
rules:
- apiGroups:
  - ko.feloy.dev
  resources:
  - kobuilders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ko.feloy.dev
  resources:
  - kobuilders/status
  verbs:
  - get
  - patch
  - update
