# permissions to do viewer kobuilders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kobuilder-viewer-role
rules:
- apiGroups:
  - ko.feloy.dev
  resources:
  - kobuilders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ko.feloy.dev
  resources:
  - kobuilders/status
  verbs:
  - get
